name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: mmedoo/build-react-on-push@v1.3
        with:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

# Script from https://github.com/marketplace/actions/build-and-publish-react